analyzer:
  errors:
    prefer_const_constructors:     prefer_const_literals_to_create_immutables: ignore
ignore
  erro ignorers:
    prefer_const_constructors: ignore
include: package:flutter_lints/flutter.yaml
